### ISSUE TITLE
Folia Bug???????

### ISSUE THREAD

**Issue by ImNotSoftik** [PaperMC/Folia#123]
### Expected behavior

Normal bed animation

### Observed/Actual behavior

https://youtu.be/esutrwDZQkg

### Steps/models to reproduce

https://youtu.be/esutrwDZQkg

### Plugin and Datapack List

[07:49:11 INFO]: Server Plugins (12):
[07:49:11 INFO]: Bukkit Plugins:
[07:49:11 INFO]:  - AnarchyExploitFixes, *BetterWorldStats, *KumorioUtils, LuckPerms, NeroChat, NoCheatPlus, PlasmoVoice, ProtocolLib, TAB, Vault
[07:49:11 INFO]:  ViaBackwards, ViaVersion

### Folia version

https://github.com/PaperMC/Folia/commit/6b978f2aafd9dd3d18a4ec2f1f5e28777763b3c7

**Comment by ocelotpotpie** [comment]
Can you reproduce this with no plugins installed?

**Comment by Spottedleaf** [comment]
This happens on CraftBukkit and above servers due to the move packet handler ignoring packets from sleeping players, which is intended and good behavior. However, the player position is not sync'd back to the player due to this, which means that it may appear to clients as if they can move - but they don't.
