### ISSUE TITLE
Explain core count recommendation 

### ISSUE THREAD

**Issue by MitchTalmadge** [PaperMC/Folia#13]
The FAQ says:

> What hardware will Folia run best on?

> Ideally, at least 16 cores (not threads).

How did this answer come about? Why "at least 16" and not 8 or 4? It confuses me because I would think anything > 1 would be an improvement over the single-threaded implementation.

Thanks.

**Comment by electronicboy** [comment]
Because the entire system needs more threads to manage the work for the threads, and then you've gotta actually have those regions do stuff, which depend on other systems which have their own threads, etc

the vanilla server software may use a single thread for the main tick loop, but, it has many other threads, and if you only have 1/2 cores, you'll be stealing time away from the main thread. The number here generally is based on internal testing with limited hardware accessibility as well as seeing how it performs (and doesn't) on the small amount of hardware we have access to. it might perform well on less cores for some use-cases, but, that's not something we can promise/test, ymmv.
