### ISSUE TITLE
Error on first player join

### ISSUE THREAD

**Issue by mani1232** [PaperMC/Folia#138]
### Expected behavior

Normal player **first** join

### Observed/Actual behavior

[message.txt](https://github.com/PaperMC/Folia/files/12159016/message.txt)
This error and timed out kick

### Steps/models to reproduce

I do not know how to repeat it, it is connected precisely with my world (on paper it works fine)

### Plugin and Datapack List

Tested with and without plugins

### Folia version

Tested with paper, Folia and Kaiju
Works fine only on paper
All cores on latest versions

### Other

Tested with and without pterodactyl
Tested with java 17-20
Tested with and without jvm fags
Tested with and without online mode

**Comment by mani1232** [comment]
(#137 old)

**Comment by mani1232** [comment]
im create new world and move from old world region and playerdata folders, it works fine (with same seed)

**Comment by YouHaveTrouble** [comment]
Are you using any kind of custom world generation? I got the same error when trying to join a new player to a world without any blocks at all, then it just got stuck in a loop of seeking the safe location to spawn them on and stack overflowed, because there was none. Solved by adding a single block to the world. Not sure if your use case is similar

**Comment by kugge** [comment]
upload the world so we can reproduce

**Comment by mani1232** [comment]
> upload the world so we can reproduce

https://drive.google.com/file/d/1_0LN4gkSxi2qIozsYWgKBfxO1VagcqAz/view?usp=sharing
