### ISSUE TITLE
After the player kills the Ender Dragon for the first time, jumping into the portal will cause the player to get stuck.

### ISSUE THREAD

**Issue by huguyt** [PaperMC/Folia#269]
### Expected behavior

After killing the Ender Dragon, jump into the portal, and when the End Poem is playing, press the ESC key to return to the main world.

### Observed/Actual behavior

After killing the Ender Dragon for the first time, jump into the portal and use ESC to skip the End Poem, which will show that the player has been falling in the End.

### Steps/models to reproduce

After starting Folia, enter the End and kill the Ender Dragon, then jump into the portal and press ESC to skip the End Poem.
(This must be the first time the ender dragon is killed after the map is generated.)

### Plugin and Datapack List

> plugins
[22:08:42 INFO]: Server Plugins (0):

### Folia version

> version
[22:09:10 INFO]: This server is running Folia version 1.21-DEV-dev/1.21@2b8c879 (2024-08-05T09:37:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

### Other

When the player is stuck in the portal, the console uses commands such as /clear player_name /kill player_name, but there is no response from the player.

**Comment by Potenza7** [comment]
+++ I have same bug.

**Comment by Potenza7** [comment]
Most of the time you get stuck when you enter the End portal and it doesn't get fixed without restarting the server.

**Comment by MineSunshineone** [comment]
i test in 9203a7a887eecdccb93a96ca460ce13364842884 
The portal from the endlands into the endlands that I tested last night looked like this:
It went straight through the portal and dropped into the space below, without returning to the main world as in the single player game
TPing through the portal was instantaneous, and then the player went into a weird state:
He can't see anyone else, they can't see him, he can't TP away, he's always online, and he can't be taken offline by kicks or bans.
After disconnecting, he can't get into the server, the server still shows the player online, the client is stuck in “after communication encryption” for a while and then shows a connection timeout, but the logs don't report any error.

After testing, the above scenario will definitely happen, and it also happens when entering from the main world, I don't know if it's because I enabled every dragon to drop dragon eggs!

Translated with DeepL.com (free version)

**Comment by andreypfau** [comment]
Same issue

**Comment by Moranyixiao** [comment]
Same issue

**Comment by Spottedleaf** [comment]
Fixed in 1.21.1 and 1.21.3 https://github.com/PaperMC/Folia/commit/06d719d57d7ca9df0bda9f881d330b05aca99ebd
