### ISSUE TITLE
Memory Leak | Leaking all entities references?

### ISSUE THREAD

**Issue by PedroMPagani** [PaperMC/Folia#283]
### Profile link

not necessary

### Description of issue

Currently there's a method that used to be called on ticking of entities, trackUnload
This used to be the method called on 1.20.6 and below:
![image](https://github.com/user-attachments/assets/051d9b95-197f-4d07-896d-387a0bcf97d2)

which would clear internally on the method, the ref list toPRocessTrackingUnloading.
ON 1.21 and upfront the method was completely forgotten, and you ended up using another ref list, called trackerUnloadedEntities

![image](https://github.com/user-attachments/assets/6a07e888-1854-433d-8b78-a94352032cfa)

This causes a leak to be present, on every single entity ever loaded by the server.

### Plugin and Datapack List

{}

### Server config files

no need for htis

### Folia version

cloned from head.

### Other

none

**Comment by PedroMPagani** [comment]
![image](https://github.com/user-attachments/assets/c00e232e-bf46-43c7-9039-30c9bb5e4363)

**Comment by Zelda-devs** [comment]
I totally agree with you. I have this problem with 1.21.1. I never had this problem with 1.20.4. I migrated my server to 1.21.1 and my server is essentially a vanilla server that aims for high entity without compromising on the experience. I use the same plugins but with the latest version 1.21.1 I can't keep my server up for more than 7-8 hours because all my ram is empty and I have to restart the server.
![image](https://github.com/user-attachments/assets/1c4bdc7d-b784-4de1-aa63-03c639e598cb)
Iron golems are spawning on my server because there are so many farms, but none of them are cleared by ram even after they die! Not only iron golems, but all farms with high mob spawns cause memory leaks on the server, and when I dump, only mob entities appear.

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Folia/commit/d8461e8ec526ad46de87d60ceee72a9cacdf6621

**Comment by mykadoo** [comment]
Yeah, that makes sense. Might be too late but I would unban this handsome guy on the donutsmp: 
Ban reason: "are we serious"💀 ~ are we deadass there is not even a time until the ban expires. Ban id:#F6TnY2u2 , ign: archievePedro. I know this name is not cool but cool enough to get unbanned ig.  Love you Pedro and your whole family. Love your wife your husband your sister your brother your cousins your aunt your uncle your grandmother your grandfather your grandma your grandpa your great grandma your great grandpa your nieces your nephews your sons your daughters your parents your mother your father your mother in law your father in law and every single member of your family no matter how far or close. Love to your whole bloodline your relatives your distant cousins your godparents your step family your in laws and everyone who stands with you and belongs to you. Sending love and respect to your entire family forever ❤️, Marry Christmas, Pedro and your wife and sister and brother mother father and idk. I hope you'll review my ban. Below you can see my face reveal and my Christmas present. 

![Image](https://github.com/user-attachments/assets/77222235-eb5f-4b0e-ab8d-7e7d05cbfe89)

![Image](https://github.com/user-attachments/assets/c9cda310-e749-4f54-86d7-923d65d26cc8)
