### ISSUE TITLE
End gateway counter reset to 0 on server restart

### ISSUE THREAD

**Issue by kugge** [PaperMC/Folia#59]
### Expected behavior

When the dragon dies, a new end gateway spawn.

### Observed/Actual behavior

When the dragon dies, old end gateways are erased (the counter restart from the beginning: 0)

### Steps/models to reproduce

1- Generate a new end
2- Kill the dragon
3- Restart
4- Summon the dragon with end crystals
5- Kill the dragon (not with /kill)
6- There is still only one end gateway

### Plugin and Datapack List

None

### Folia version

```
[20:30:19 INFO]: This server is running Folia version git-Folia-"17a3236" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 17a3236)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
```
Note: Reproductible on latest build

### Other

The gateway counter is not saved correctly on shutdown ?

**Comment by Spottedleaf** [comment]
This isn't a Folia issue. I suspect this is a Vanilla issue. 

This is due to the fact that Mojang has shoved in their DFU Dynamic / Codec system into the load process for the server level data and it changes the stored gateway type from a List of Ints to an Int Array tag, and as such the deserialization code cannot read it properly. Yet another reason to hate it for being far too abstract.

If you can test on Vanilla, report to them. I'm not touching this system at all, as it's far too complicated to judge whether any fix I make would break anything (see previous attempts to fix the MapCodec log spam).
